# Generated by Django 2.1.2 on 2018-10-27 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=250)),
                ('product', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AsinList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NAGammaStandardAsinExpiry.Asin')),
            ],
        ),
    ]
